[package]
name = "prediction-ledger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
ratatui = {version = "0.26.2", features=["all-widgets"]}
time = {version="0.3.36", features=['local-offset', 'formatting', 'macros']}
